- name: catalogue server
  become: yes
  hosts: catalogue
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present
  
  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: creating roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: yes
     home: /app
     shell: /sbin/nologin

  - name: downloading catalogue code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip

  - name: extracting or unzipping catalogue code
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes

  - name: installing dependicies
    community.general.npm:
     path: /app
     state: present

  - name: copying catalogue service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes

  - name: copy mongo repo file
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: installing client software
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present

  - name: check products loaded or not if catalogue db exits or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue_output
    ansible.builtin.debug:
     msg: "{{ catalogue_output }}"

  - name: load products if catalogue db doesnot exists
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    


  
